---
- name: pull Rancher/server container
  docker_image:
    name: rancher/server:latest
  when: docker_installed is success

- name: Create mount volume directories for persistent rancher server data
  file: path={{ item.path }} state=directory mode="a+rw"
  with_items:
      - { path: '/opt/rancher/lib/mysql' }
      - { path: '/opt/rancher/log/mysql' }
      - { path: '/opt/rancher/lib/cattle' }

- name: Run Rancher server
  docker_container:
    name: rancher
    image: rancher/server:latest
    restart_policy: unless-stopped
    ports:
     - "8080:8080"
     - "9345:9345"
    volumes:
      - /opt/rancher/lib/cattle:/var/lib/cattle
      - /opt/rancher/lib/mysql:/var/lib/mysql
      - /opt/rancher/log/mysql:/var/log/mysql

- name: Wait for the Rancher server to start
  action: command docker logs rancher
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 30
  delay: 10
