---
- name: Check if auth is enabled
  uri:
    method: GET
    status_code: 401
    url: "http://{{ rancher_server }}:{{ rancher_port }}/v1"
  register: auth_enabled
  ignore_errors: yes

- name: Add API access key to admin account
  uri:
      method: POST
      status_code: 201
      force_basic_auth: yes
      user: "{{ api_user }}"
      password: "{{ api_pass }}"
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/apikeys"
      body_format: json
      body: "{{ create_api_key_body | to_json }}"
  when: auth_enabled is failed

- name: Enable local authentication and setup rancher server admin user
  uri:
      method: POST
      status_code: 201
      force_basic_auth: yes
      user: "{{ api_user }}"
      password: "{{ api_pass }}"
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/localauthconfigs"
      body_format: json
      body: "{{ enable_local_auth_body | to_json }}"
  when: auth_enabled is failed

- name: Confirm admin access to API
  uri:
      method: GET
      status_code: 200
      force_basic_auth: yes
      user: "{{ api_user }}"
      password: "{{ api_pass }}"
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1"

- name: Get the default project id
  uri:
      method: GET
      status_code: 200
      force_basic_auth: yes
      user: "{{ api_user }}"
      password: "{{ api_pass }}"
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/projects"
      return_content: yes
  register: project_id

- name: Return the registration token URL of Rancher server
  uri:
      method: POST
      status_code: 201
      force_basic_auth: yes
      user: "{{ api_user }}"
      password: "{{ api_pass }}"
      url: "http://{{ rancher_server }}:{{ rancher_port }}/v1/registrationtokens?projectId={{ project_id.json['data'][0]['id'] }}"
      return_content: yes
  register: rancher_token_url

- name: Return the registration URL of Rancher server
  uri:
      method: GET
      status_code: 200
      force_basic_auth: yes
      user: "{{ api_user }}"
      password: "{{ api_pass }}"
      url: "{{ rancher_token_url.json['links']['self'] }}"
      return_content: yes
  register: rancher_token
